
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /app-authors/ {
        proxy_pass http://authors:8080/;
    }

    location /app-books/ {
        proxy_pass http://books:8080/;
    }
}



