-- TABLAS DEL MÓDULO app-books
CREATE TABLE books_authors
(
    book_isbn  VARCHAR(255) NOT NULL,
    authors_id INTEGER      NOT NULL,
    CONSTRAINT pk_books_authors PRIMARY KEY (book_isbn, authors_id)
);

ALTER TABLE books_authors
    ADD CONSTRAINT FK_BOOKS_AUTHORS_ON_AUTHORS FOREIGN KEY (authors_id) REFERENCES authors (id);


CREATE TABLE books
(
    isbn    VARCHAR(255) NOT NULL,
    version INTEGER,
    title   VARCHAR(255),
    price   DOUBLE PRECISION,
    CONSTRAINT pk_books PRIMARY KEY (isbn)
);

CREATE TABLE inventory
(
    book_isbn VARCHAR(255) NOT NULL,
    sold      INTEGER,
    supplied  INTEGER,
    version   INTEGER,
    CONSTRAINT pk_inventory PRIMARY KEY (book_isbn)
);

ALTER TABLE inventory
    ADD CONSTRAINT FK_INVENTORY_ON_BOOK_ISBN FOREIGN KEY (book_isbn) REFERENCES books (isbn);



-- TABLAS DEL MÓDULO app-customers
CREATE TABLE customer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          name VARCHAR(255),
                          email VARCHAR(255),
                          version INTEGER,
                          CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE purchaseorder (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               customer_id BIGINT,
                               deliveredon TIMESTAMP,
                               placedon TIMESTAMP,
                               status INTEGER,
                               total INTEGER,
                               CONSTRAINT pk_purchaseorder PRIMARY KEY (id),
                               CONSTRAINT fk_po_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE lineitem (
                          order_id BIGINT NOT NULL,
                          idx INTEGER NOT NULL,
                          book_isbn VARCHAR(255),
                          quantity INTEGER,
                          CONSTRAINT pk_lineitem PRIMARY KEY (order_id, idx),
                          CONSTRAINT fk_li_order FOREIGN KEY (order_id) REFERENCES purchaseorder(id),
                          CONSTRAINT fk_li_book FOREIGN KEY (book_isbn) REFERENCES books(isbn)
);