CREATE TABLE authors
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

INSERT INTO authors (name) VALUES
                               ('Gabriel García Márquez'),
                               ('Isabel Allende'),
                               ('Julio Cortázar');



